export const lootTable = [
    // Objets communs
    { name: 'Boîte de conserve', rarity: 'common', id: 1, icon: '/assets/items/can_001.png' },
    { name: 'Bouteille d\'eau', rarity: 'common', id: 2, icon: '/assets/items/bottle_001.png' },
    { name: 'Sac à dos', rarity: 'common', id: 3, icon: '/assets/items/backpack_001.png' },
    { name: 'Corde', rarity: 'common', id: 4 },
    { name: 'Couteau de chasse', rarity: 'common', id: 5, icon: '/assets/items/knife_001.png' },
    { name: 'Vieux journal', rarity: 'common', id: 6 },
    { name: 'Briquet usé', rarity: 'common', id: 7, icon: '/assets/items/lighter.png' },
    { name: 'Pile déchargée', rarity: 'common', id: 8, icon: '/assets/items/battery_001.png' },
    { name: 'Cartouche vide', rarity: 'common', id: 9 },
    { name: 'Lampe torche (cassée)', rarity: 'common', id: 10, icon: '/assets/items/flashlight.png' },
    { name: 'Couverture en laine', rarity: 'common', id: 11 },

    // Objets rares
    { name: 'Trousse de premiers soins', rarity: 'rare', id: 12 },
    { name: 'Munition', rarity: 'rare', id: 13 },
    { name: 'Ration militaire', rarity: 'rare', id: 14 },
    { name: 'Lampe torche', rarity: 'rare', id: 15, icon: '/assets/items/flashlight.png' },
    { name: 'Système de filtration d\'eau', rarity: 'rare', id: 16 },
    { name: 'Couteau de survie', rarity: 'rare', id: 17, icon: '/assets/items/knife_001.png' },
    { name: 'Radio portable', rarity: 'rare', id: 18 },
    { name: 'Masque à gaz', rarity: 'rare', id: 19 },
    { name: 'Batterie de secours', rarity: 'rare', id: 20 },
    { name: 'Boîte de vitamines', rarity: 'rare', id: 21 },
    { name: 'Plan de survie', rarity: 'rare', id: 22 },

    // Objets très rares
    { name: 'Arme de mêlée', rarity: 'very_rare', id: 23 },
    { name: 'Jumelles de précision', rarity: 'very_rare', id: 24 },
    { name: 'Gilet pare-balles', rarity: 'very_rare', id: 25 },
    { name: 'Arbalète', rarity: 'very_rare', id: 26 },
    { name: 'Trousse médicale complète', rarity: 'very_rare', id: 27 },
    { name: 'Détecteur de métaux', rarity: 'very_rare', id: 28 },
    { name: 'Flare de détresse', rarity: 'very_rare', id: 29 },
    { name: 'Cagoule thermique', rarity: 'very_rare', id: 30 },
    { name: 'Tenue camouflée', rarity: 'very_rare', id: 31 },
    { name: 'Chargeur plein', rarity: 'very_rare', id: 32 },

    // Objets légendaires
    { name: 'Objet unique', rarity: 'legendary', id: 33 },
    { name: 'Carte d\'accès spéciale', rarity: 'legendary', id: 34 },
    { name: 'Disque dur crypté', rarity: 'legendary', id: 35 },
    { name: 'Prototype d\'arme expérimentale', rarity: 'legendary', id: 36 },
    { name: 'Générateur portable', rarity: 'legendary', id: 37 },
    { name: 'Trousse d\'outils avancée', rarity: 'legendary', id: 38 },
    { name: 'Armure anti-émeute', rarity: 'legendary', id: 39 },
    { name: 'Ordinateur de terrain', rarity: 'legendary', id: 40 },
    { name: 'Relique mystérieuse', rarity: 'legendary', id: 41 },
    { name: 'Radioactive Suit', rarity: 'legendary', id: 42 },
];
